### ISSUE TITLE
LiveStreaming not working, it was working but now from few days it is not working

### ISSUE THREAD

**Issue by abhinavjiit** [AgoraIO/API-Examples#107]
<img width="616" alt="截屏2020-12-27 下午2 42 57" src="https://user-images.githubusercontent.com/8169775/103165414-786f2480-4852-11eb-83aa-b5e919dfad2c.png">

**Comment by plutoless** [comment]
@abhinavjiit sorry it's not working from which perspective?

**Comment by plutoless** [comment]
ok i saw the issue in the other ticket. we will take a look ASAP

**Comment by yoreland** [comment]
moved the issue screenshoot from another post.
@abhinavjiit Seems your are reproduce this issue on your own app, right?
I can't reproduce the same issue on ApiExample. But if you are just use setClientRole to board caster, can you use 

setClientRole (  int role ) without clientRoleOption? will this cause crash also?

**Comment by abhinavjiit** [comment]
Yes I have used that one also, it is not crashing when I don't use
clientoptions  but  as I sent you screenshots, you can see that Rtcengine
instance, client role is showing as audience, even I am setting it as
broadcaster because of that livestream not working. Pls go through the
screenshots once again.

**Comment by yoreland** [comment]
btw, this option is available only from 3.2.0.
can you make sure both sdk jar and so sdk files are updated to latest?
Seems the Live Streaming Demo in APIExample can't reproduce your issue..
