### ISSUE TITLE
Is it possible to rename MultiProcess.java as MultiProcessScreenSharing.java?

### ISSUE THREAD

**Issue by yamasite** [AgoraIO/API-Examples#111]
As a demo project, users may find **MultiProcessScreenSharing.java** easier to understand than **MultiProcess.java**.

https://github.com/AgoraIO/API-Examples/blob/master/Android/APIExample/app/src/main/java/io/agora/api/example/examples/advanced/MultiProcess.java

**Comment by yoreland** [comment]
Thanks for suggestion. 
As there is already another example for screen sharing. The example is for just show how to publish two stream simultaneously.
