### ISSUE TITLE
FOR windows the "installThirdParty.bat" has error.

### ISSUE THREAD

**Issue by LeoBline** [AgoraIO/API-Examples#115]
I can't success run the bat file.
I find there is a issue in the insteal.ps1
![image](https://user-images.githubusercontent.com/50190407/104263767-32a69300-54c5-11eb-91ff-43c144b1089c.png)
A single quotation mark is missing here, causing batch processing to never install normally.

**Comment by plutoless** [comment]
umm 
![image](https://user-images.githubusercontent.com/471561/104843482-e06ed300-5905-11eb-9a8e-1d58794fafe3.png)
for me it's there?

**Comment by LeoBline** [comment]
ummm,i don't know why this happen  to me .... maybe my fault.........Thanks

**Comment by LeoBline** [comment]
by the way,Do you guys plan to support sharing screen sound in Windows Sharing Screen ?

**Comment by plutoless** [comment]
you may call enableLoopbackRecording to share your system sound to remote. be careful as this may cause echo.

**Comment by LeoBline** [comment]
Thats sooo goood ! Thanks for you help.
