### ISSUE TITLE
Binary rejected : The app references non-public selectors

### ISSUE THREAD

**Issue by rajdhakate** [AgoraIO/API-Examples#116]
Hi,

I've updated to v3.3.0 and uploaded the app on AppStore connect. Got an issue from Apple after the app was processed.

> We identified one or more issues with a recent delivery for your app, AppName. Please correct the following issues, then upload again.
> 
> ITMS-90338: Non-public API usage - The app references non-public selectors in AppName: netServiceBrowser:didRemoveService:, setUid:, stopPreview, transform:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by plutoless** [comment]
@rajdhakate hi 3.3.0 does not have any static library they are all dynamic. do you have a reproducible project so that we can help you take a look?

**Comment by rajdhakate** [comment]
Hi. Sorry for late reply. The issue can be reproduced by just adding the Agora pod in project and distributing app in Testflight. Since the distribution is involved I'm not sure if I can provide any sample project.

**Comment by plutoless** [comment]
@rajdhakate does this even happen if you start a new project and just put agora sdk in?

**Comment by twentyone24** [comment]
```

 @return * 0: Success.
* < 0: Failure.
 */
- (int)startPreview;

/** Stops the local video preview and the video.

 @return * 0: Success.
* < 0: Failure.
 */
- (int)stopPreview;
- 
````

So, here in the Agora SDK, there are functions, like `startPreview` & `stopPreview` 
That seems to be the issue, it seems.

**Comment by tamworth** [comment]
@rajdhakate if there are still issues, you might want to try upgrading the SDK version.
