### ISSUE TITLE
Cannot resolve symbol DataStreamConfig

### ISSUE THREAD

**Issue by susheeltandon** [AgoraIO/API-Examples#125]

**Comment by yoreland** [comment]
which platform and sdk version you are using?
this DataStreamConfig is avaiable since sdk 3.3.0

**Comment by susheeltandon** [comment]
I am using 3.2.0, will update thanks

**Comment by susheeltandon** [comment]
I am integrating video call on one to one basis, client initiate video chat and other person accept chat and initiate it. Which classes I will use for that ? Is any example of that.

**Comment by yoreland** [comment]
there is another demo for call invitation, which need introduce RTM.
please check https://github.com/AgoraIO-Usecase/Video-Calling

**Comment by susheeltandon** [comment]
Ok I will thanks

**Comment by susheeltandon** [comment]
hello Sir I am getting error in basic video call 

E/libc: Access denied finding property "net.dns1"

**Comment by plutoless** [comment]
@susheeltandon you may simply ignore it.

**Comment by susheeltandon** [comment]
Ok

**Comment by susheeltandon** [comment]
Hello Sir,  I have implemented entire code as per 1to1 video chat from Agora documentation, how my userid will call one of my client userid through App, where I will put my userid and client userid.

**Comment by susheeltandon** [comment]
Also getting this message
Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.samsung.adaptivebrightnessgo API Level 2

**Comment by plutoless** [comment]
@susheeltandon i guess you want to notify the other phone to join a video call.
please check this example in this case,
https://github.com/AgoraIO-Usecase/Video-Calling

**Comment by susheeltandon** [comment]
Yes plutoless, you are right I want to notify other phone to join call, I will check thanks

**Comment by susheeltandon** [comment]
Where, I will set current user who is calling and remote user who is responding.
