### ISSUE TITLE
render crash

### ISSUE THREAD

**Issue by zhanghemama** [AgoraIO/API-Examples#130]
<img width="1186" alt="Screen Shot 2021-02-22 at 3 24 04 PM" src="https://user-images.githubusercontent.com/34675844/108675916-6512c980-7522-11eb-848d-60f9b15bd2b5.png">

render crash, please refer to attached file

**Comment by zhanghemama** [comment]
validateFunctionArguments:3714: failed assertion `Vertex Function(mapTexture): missing buffer binding at index 0 for vertex_array[0].'
validateFunctionArguments:3714: failed assertion `Vertex Function(mapTexture): missing buffer binding at index 0 for vertex_array[0].'

**Comment by yoreland** [comment]
Thanks for report.
Could you provide device model and os version? When you reproduce this issue, what is the device you uses for remote user?

**Comment by zhanghemama** [comment]
都是苹果自带的摄像头，crash 机器的系统是11.0.1

**Comment by yoreland** [comment]
Sorry for confusing, as two platform code are similar, can you help double confirm it is for Mac OS not for iOS, right?

**Comment by zhanghemama** [comment]
<img width="1123" alt="Screen Shot 2021-03-01 at 10 06 28 AM" src="https://user-images.githubusercontent.com/34675844/109443642-072c3780-7a76-11eb-9620-2cdc27b3c0f2.png">

it seems that textures are bad memory

**Comment by zhanghemama** [comment]
MACOS10.15也有第一个crash， validateFunctionArguments:3476: failed assertion `Vertex Function(mapTexture): missing buffer binding at index 0 for vertex_array[0].'

**Comment by yoreland** [comment]
在iOS项目中我们的确发现之前有个render crash问题修复见如下两个commit

https://github.com/AgoraIO/API-Examples/commit/1d6ee5f47d32e48f351fd2a3daa4bc48eb05b51e
https://github.com/AgoraIO/API-Examples/commit/73e6df34659cc74f54c7fe3cebccd95ce87086ad

您可以快速参考一下这个修改,我们这边也会做个验证并且merge到macOS的示例中

**Comment by zhanghemama** [comment]
你好代码你merge到macOS了吗

**Comment by yoreland** [comment]
参考下这个分支？
https://github.com/AgoraIO/API-Examples/tree/dev/3.3.1

**Comment by yoreland** [comment]
just merged to master
