### ISSUE TITLE
In Screen share, Start broadcast not working in iOS 14

### ISSUE THREAD

**Issue by sapankajbhalala** [AgoraIO/API-Examples#131]
screen sharing not working when start broadcast from Live Broadcast Popup, 
And some time giving this error message popup
![image](https://user-images.githubusercontent.com/50910459/108703075-2552de80-7530-11eb-9116-de1ae350b721.png)

`AgoraUploader.startBroadcast(to: "CHANNEL_NAME")`

Specially it's not working in iOS 14 device.
I have checked it's with iOS 13 device and it's working.

**Comment by Apiphoom** [comment]
yep I have that problem too

**Comment by yoreland** [comment]
@sapankajbhalala We did some test on ios14 devices but currently can't reproduce the issue.
Can I know which device model you are using? There is one known issue that the replay kit extension could be crashed when available runtime memory less than 50M.

**Comment by dhavalSA** [comment]
i am having same issue. i did check that the reason for this issue is extension's memory use get increased more then 50 MB which ultimately crash the  extension  thats why this popup comes. 

i have implemented it same as shown in Example project . still having this issue . i have check with different devices . it run properly for some time and then memory goes to above 50 . 
can anyone guide me how to mange this memory limit . and what is the reason for this memory increase while integrating same as example project .
i also check same in example project. in example project its not increasing memory . is there any configuration which i missed ?
one more thing is if i comment " sharedAgoraEngine.pushExternalVideoFrame(frame)" this line then memory stays in limit 

Thanks

**Comment by yoreland** [comment]
> i am having same issue. i did check that the reason for this issue is extension's memory use get increased more then 50 MB which ultimately crash the extension thats why this popup comes.
> 
> i have implemented it same as shown in Example project . still having this issue . i have check with different devices . it run properly for some time and then memory goes to above 50 .
> can anyone guide me how to mange this memory limit . and what is the reason for this memory increase while integrating same as example project .
> i also check same in example project. in example project its not increasing memory . is there any configuration which i missed ?
> one more thing is if i comment " sharedAgoraEngine.pushExternalVideoFrame(frame)" this line then memory stays in limit
> 
> Please guide me
> Thanks

Thanks for the detailed information. Will check on this point and update ASAP

**Comment by dhavalSA** [comment]
@yoreland is there any workaround for this issue.

**Comment by yoreland** [comment]
> @yoreland is there any workaround for this issue.
we just have some insight of this issue. For bitrate control purpose, SDK will buffer some data for video encoding strategy. 
After testing on several different devices. It is found that if setting video encoding configuration as CGSize(width: 540, height: 960), the sharing will keep stays in limit.

**Comment by dhavalSA** [comment]
i checked this , in AgoraUploader i did this modification 
private static let videoDimension : CGSize = {
        let screenSize = UIScreen.main.currentMode!.size
        var boundingSize =  CGSize(width: 540, height: 960)
        let mW = boundingSize.width / screenSize.width
        let mH = boundingSize.height / screenSize.height
        if( mH < mW ) {
            boundingSize.width = boundingSize.height / screenSize.height * screenSize.width
        }
        else if( mW < mH ) {
            boundingSize.height = boundingSize.width / screenSize.width * screenSize.height
        }
        return boundingSize
    }() 

bound size reduced to  var boundingSize =  CGSize(width: 540, height: 960)

now frequency of this issue is reduced but still issue some times having this issue .

**Comment by dhavalSA** [comment]
it seems like when internet goes down or device is bit slow it goes beyond 50 MB .

**Comment by yoreland** [comment]
Thanks for the info. We check on this scenario also and update you.

**Comment by yoreland** [comment]
> it seems like when internet goes down or device is bit slow it goes beyond 50 MB .

@dhavalSA From SDK level it is under optimizing, the problem will be resolved for future release.
But for currently, you could only limit resolution and frame rate.
You could use setVideoEncoderConfiguation API to modify framerate

**Comment by dhavalSA** [comment]
@yoreland Thanks for this solution . when we can expect new release with optimised memory issue with proper fix .

**Comment by jingliancui** [comment]
And then , same problem meet : )

**Comment by yoreland** [comment]
The fix is still working in progress, as it need an optimization on video encoder part. The fix is scheduled on 3.5.0 version.

**Comment by dhavalSA** [comment]
@yoreland Thanks ,Please notify us when 3.5.0 version is available

**Comment by mahadhaq** [comment]
@yoreland When ever I start broadcasting after some time popup appears
![IMG_7391](https://user-images.githubusercontent.com/46572644/115711939-9aeef580-a38d-11eb-85f7-278e184bf94a.jpg)

**Comment by yoreland** [comment]
> @yoreland When ever I start broadcasting after some time this popup appears? Is there any solution
> ![IMG_7391](https://user-images.githubusercontent.com/46572644/115711939-9aeef580-a38d-11eb-85f7-278e184bf94a.jpg)

should be same reason as above discussed. The workaround for now is reduce frame rate and resolution on vidoEncoder configuration

**Comment by mahadhaq** [comment]
> > @yoreland When ever I start broadcasting after some time this popup appears? Is there any solution
> > ![IMG_7391](https://user-images.githubusercontent.com/46572644/115711939-9aeef580-a38d-11eb-85f7-278e184bf94a.jpg)
> 
> should be same reason as above discussed. The workaround for now is reduce frame rate and resolution on vidoEncoder configuration

But the issue is still occuring after reducing the frame rate and resolution

**Comment by koogawa** [comment]
Same problem. When will 3.5.0 be released?

**Comment by s1lviu** [comment]
Still have this problem on 3.5.0.3. Any update?

**Comment by jonah-katz** [comment]
any update?

**Comment by tamworth** [comment]
@sapankajbhalala you can try again using the new version of the API-Example.
