### ISSUE TITLE
Custom Audio Source / Rendering is not working

### ISSUE THREAD

**Issue by abthulrazeeth** [AgoraIO/API-Examples#136]
I am trying to check the custom audio source and rendering. I see the data being sent and received, however i don't see any playback. I get a 1020 warning.

**Comment by plutoless** [comment]
@abthulrazeeth which platform

**Comment by abthulrazeeth** [comment]
@plutoless  It is Android.

**Comment by thkim0118** [comment]
Not working too.
I got a 1020 warning in Android.

**Comment by yoreland** [comment]
Can you provide full log trace here?
@thkim0118 @abthulrazeeth
Do you feel capture and rendering both not working?

**Comment by thkim0118** [comment]
I just use your example project.

1. When I select 'Custom Audio Source/Renderer', I got a this log messages.
![스크린샷 2021-04-19 오전 10 39 36](https://user-images.githubusercontent.com/56363632/115170452-a88d4c80-a0fb-11eb-99b5-b9f4fc6d7ce5.png)

2. Here is the messages when I join the channel.
![스크린샷 2021-04-19 오전 10 42 50](https://user-images.githubusercontent.com/56363632/115170629-06ba2f80-a0fc-11eb-8915-011846705a47.png)

3. Here is the messages when other user is joined the channel.
![스크린샷 2021-04-19 오전 10 47 27](https://user-images.githubusercontent.com/56363632/115170865-a5df2700-a0fc-11eb-951b-cf52ad66ae6b.png)

+ I got a this error messages when I click the back button while using 'Custom Audio Source/Renderer'.
![스크린샷 2021-04-19 오전 10 48 19](https://user-images.githubusercontent.com/56363632/115171003-01a9b000-a0fd-11eb-8efd-5abb2ba1e319.png)

**Comment by yoreland** [comment]
OK, seems your issue is on custom renderer only. Do you have chance to verify on any other device?

**Comment by thkim0118** [comment]
I have 'Samsung Galaxy note 8'.
It has same issue.
Here is the log messages.
![Uploading 스크린샷 2021-04-19 오후 3.40.36.png…]()

**Comment by yoreland** [comment]
@thkim0118 Can you check (this code)[https://github.com/AgoraIO/API-Examples/blob/dev/3.4.0/Android/APIExample/app/src/main/java/io/agora/api/example/examples/advanced/customaudio/CustomAudioSource.java] 
We do have some fix on this example and is about to merge to master very soon

**Comment by thkim0118** [comment]
Your code is working well. Thanks :)

Is this final code to merge in master branch?

**Comment by bandrarom** [comment]
> @thkim0118 Can you check [this code](https://github.com/AgoraIO/API-Examples/blob/dev/3.4.0/Android/APIExample/app/src/main/java/io/agora/api/example/examples/advanced/customaudio/CustomAudioSource.java) We do have some fix on this example and is about to merge to master very soon

i try to open that link it doesn't work. I am also stuck in externa audio streaming
