### ISSUE TITLE
not able to ope the app

### ISSUE THREAD

**Issue by snehagpt923** [AgoraIO/API-Examples#137]
getting crash with below error as soon I am launching the app.
Process: io.agora.tutorials1v1acall, PID: 4765
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.agora.tutorials1v1acall-7raLUzc8PZu31RWWrMcrbg==/base.apk", zip file "/data/app/io.agora.tutorials1v1acall-7raLUzc8PZu31RWWrMcrbg==/split_config.en.apk", zip file "/data/app/io.agora.tutorials1v1acall-7raLUzc8PZu31RWWrMcrbg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/io.agora.tutorials1v1acall-7raLUzc8PZu31RWWrMcrbg==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libagora-core.so"

**Comment by yoreland** [comment]
This error means you didn't integrate Agora native sdk so library into your project.
Can you double confirm which repo you are running(As from your log it shows as "io.agora.tutorials1v1acall")? You could try to use grade to sync Agora SDK into your project

**Comment by snehagpt923** [comment]
Yes.. it worked after i added sdk. I missed it previously. Thanks for your
help.

Regards,
Sneha Gupta
