### ISSUE TITLE
Android Voice SDK: What are the permissions used for ?

### ISSUE THREAD

**Issue by vshivam** [AgoraIO/API-Examples#141]
Hi, the Agora voice call guide [here](https://docs.agora.io/en/Voice/start_call_audio_android?platform=Android) says, request for permissions as needed. 

I have not yet been able to find which permissions are needed to use which feature of Agora voice SDK. There used to be `READ_PHONE_STATE` and `BLUETOOTH` in the list as well but it seems it is not needed anymore. Could you please point me to some relevant documentation where I could find this information.

**Comment by yoreland** [comment]
You could check 
https://docs.agora.io/en/Interactive%20Broadcast/faq/ios_bluetooth 
you could add these two permission for Check if the Bluetooth device supports SCO. And provide user friendly notifications
