### ISSUE TITLE
Co-hosting channel media Relay failed at error code 2

### ISSUE THREAD

**Issue by jameelspario** [AgoraIO/API-Examples#145]
Join Channel Info
channel 1 : spario 
uid1 : 1234
token 1: I generate from server using channel1 and uid1

channel 2 :lyf
uid2 : 1235
token 2: Generated using channel2 and uid2

channel media relay info for 'spario' channel:
Source channel -> 
channel : spario,
uid: 0, 

token generated by spario channel and uid=0
Destination channel -> 
channel : lyf, 
uid: 1235,

token generated by 'spario' channel and uid=1235  
channel media relay info for 'lyf' channel:
Source channel -> 
channel : lyf, 
uid: 0, 

token generated by 'lyf' channel and uid=0
Destination channel ->
channel : spario, 
uid: 1234,

token generated by spario channel and uid=1234  

Note: Token for channel media relay is generated by the same method as for joining channels.
still I get Channel media relay error code 2

Co host token authentication enabled from Agora console

**Comment by plutoless** [comment]
@jameelspario i believe you will need to contact support team to turn on this feature.

**Comment by jameelspario** [comment]
I already have turned the feature on, Now I get error code 1 : RELAY_ERROR_SERVER_ERROR_RESPONSE(1): An error occurs in the server response. from onChannelMediaRelayStateChanged callback method. Could you please guide me to set destination ChannelMediaInfo, as I set it the Destination channel (which is remote channel name), destination uid (uid of remote broadcaster), and token generated from both of these.... for source cahnnel media info it is the channel name of local broacaster, uid = 0, nd token generated from both of these..... Thanks  in advance.

**Comment by tamworth** [comment]
@jameelspario  sorry for the late reply. you can try our latest 4.x SDK. If you still have problems, you can contact the support team to inquire about the specific reason for you
