### ISSUE TITLE
Can't find IExternalVideoInputService class

### ISSUE THREAD

**Issue by yhhCh405** [AgoraIO/API-Examples#146]
Can I view IExternalVideoInputService class? I can't find it in `io.agora.advancedvideo.externvideosource.IExternalVideoInputService` as provided in example. Thanks

**Comment by yoreland** [comment]
![image](https://user-images.githubusercontent.com/8169775/113694354-392e5a80-9702-11eb-8de0-0daae840c28c.png)
You could check here

**Comment by yhhCh405** [comment]
I got it. Thanks

**Comment by the-kool-sk** [comment]
Can't find...
