### ISSUE TITLE
Local blur doesn't work using onCaptureVideoFrame lib-raw-data in android

### ISSUE THREAD

**Issue by Jack29913** [AgoraIO/API-Examples#149]
This is reproducible in sample project as well. We see onCaptureVideoFrame callback is being called and when we debug we can see the blurred bitmap (it's rotation also wrong) but the line below doesn't seem to be doing anything. It doesn't apply the blur to the frame itself.

`System.arraycopy(YUVUtils.bitmapToI420(width, height, bmp), 0, data, 0, bufferLength);`

In our own code we directly change data array's content but it also doesn't work with the new SDK.

Can you give assistance ASAP @yoreland ?

**Comment by yoreland** [comment]
For local blur, you may need to process it from "onRenderVideoFrame".

Just a question, for your project, do you check if your blur is take effect. But just can't push the blurred bitmap back to SDK?

**Comment by Jack29913** [comment]
onRenderVideoFrame is for remote frame, it even has uid. Its not for local blur. Also we use onCaptureVideoFrame for old sdk and it works just fine.

Yes blurred data can't be pushed to SDK, that's the problem.

**Comment by yoreland** [comment]
It has been fix on dev/3.4.0 branch.

you could find below code for correction:

```
void writebackVideoFrame(VideoFrame &videoFrame, void *byteBuffer)
{
    if (byteBuffer == nullptr)
    {
        return;
    }

    int width = videoFrame.width;
    int height = videoFrame.height;
    size_t widthAndHeight = (size_t) videoFrame.yStride * height;

    memcpy(videoFrame.yBuffer, byteBuffer, widthAndHeight);
    memcpy(videoFrame.uBuffer, (uint8_t *) byteBuffer + widthAndHeight, widthAndHeight / 4);
    memcpy(videoFrame.vBuffer, (uint8_t *) byteBuffer + widthAndHeight * 5 / 4,
           widthAndHeight / 4);
}
```

**Comment by Jack29913** [comment]
okay that solved it, thank you. when will this pushed to master branch?

**Comment by yoreland** [comment]
suppose early next week
