### ISSUE TITLE
Raw Audio Data is not working.

### ISSUE THREAD

**Issue by thkim0118** [AgoraIO/API-Examples#151]
I'm inquiring because there was a problem while studying 'Raw Audio Data'.

I have two questions.

The first question.
The test environment is as follows:
Audio communication was performed using 'Raw Audio Data' on one side and 'Basic Audio Streaming' on the other.

Abnormal audio was sent from 'Raw Audio Data' when 'Basic Audio Streaming' transmitted audio after accessing the channel on both sides.
When the channel is left in 'Raw Audio Data' and reconnected, audio from 'Raw Audio Data' is transmitted normally.

The above issue occurs when the activity ends and re-runs in 'Raw Audio Data'.

The second question.
When 'Raw Audio Data' sent audio in the environment above, 'Basic Audio Streaming' did not receive audio.

Is it right that I can't get it from Basic Audio Streaming because there's no transmitter in 'Raw Audio Data'?

Thank you.

**Comment by yoreland** [comment]
can you try with below fix?
```
            engine.setRecordingAudioFrameParameters(SAMPLE_RATE, SAMPLE_NUM_OF_CHANNEL, Constants.RAW_AUDIO_FRAME_OP_MODE_READ_ONLY, SAMPLES_PER_CALL);
            engine.setMixedAudioFrameParameters(SAMPLE_RATE, SAMPLES_PER_CALL);
            engine.setPlaybackAudioFrameParameters(SAMPLE_RATE, SAMPLE_NUM_OF_CHANNEL, Constants.RAW_AUDIO_FRAME_OP_MODE_READ_ONLY, SAMPLES_PER_CALL);
            mAudioPlayer = new AudioPlayer(AudioManager.STREAM_VOICE_CALL, SAMPLE_RATE, SAMPLE_NUM_OF_CHANNEL, AudioFormat.CHANNEL_OUT_MONO);
```
 it is just about to update on master branch

**Comment by thkim0118** [comment]
It works fine! Thanks :)
