### ISSUE TITLE
Mac OS not working

### ISSUE THREAD

**Issue by HenryRocken** [AgoraIO/API-Examples#158]
Can you help to check whether the examples of Mac OS version works?

Log from xcode: 
"2021-05-21 19:04:24.860906+0800 APIExample[10433:192215] The class 'CocoaRenderView' overrides the method setIdentifier:.  This method is implemented by class 'NSView'
Warning: warning: 8
2021-05-21 19:04:24.917550+0800 APIExample[10433:192573] [] CMIOHardware.cpp:379:CMIOObjectGetPropertyData Error: 2003332927, failed
Warning: warning: 104
Warning: warning: 104
Warning: warning: 104
Warning: warning: 104
"
my network works fine, and the parameters works fine 
i am not able to find the success of the joinchannel
agorasdk.log 

"INFO    (18:57:33:948 |    0)   9735; [ap] GenericUniLbsRequest, flag: 65536, cname: 11C755428F394B399C8F33088E97F9A9, uid: 0,sid: F31B96BE90824AF48BBC94BA03B4BE12, appid: 896929e2b84c4c16917a0dc21676bbc
INFO    (18:57:33:948 |    0)   9735; [ap] tcp - creating channel with 184.72.18.217:8443, ts 0, flag: 65536
INFO    (18:57:33:998 |   50)   9735; [remote:54.178.26.110:8443] on connection close received, reason: 0, detail:
INFO    (18:57:33:998 |    0)   9735; [remote:54.178.26.110:8443] start time wait, duration: 2000 ms
ERROR   (18:57:33:998 |    0)   9735; [ap] aut socket error with 54.178.26.110:8443
INFO    (18:57:33:998 |    0)   9735; [remote:54.178.26.110:8443] destroy session 0x7fee8f877eb0
INFO    (18:57:33:998 |    0)   9735; [remote:54.178.26.110:8443] destroy connection 0x7fee8f0bd000
INFO    (18:57:34:269 |    0)   9735; [ap/t] **responsed from 184.72.18.217:8443, UDPPROXY(65536).
INFO    (18:57:34:360 |   91)   9735; [ap/u] **responsed from 15.237.134.178:8443, UDPPROXY(65536).

**Comment by yoreland** [comment]
Just for confirmation, can you use same appID on this demo:
https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/

and check if it work?

**Comment by HenryRocken** [comment]
appID works fine. 
I used the same appID and token in the IOS demo and some other demos.

**Comment by HenryRocken** [comment]
Default is no use proxy, and proxy initialized with "1"  "udpProxy = 1"

change the defaultProxySettingIdx: Int = 0 and change the order of Proxy
    static var defaultProxySettingIdx: Int = 0
    static var Proxy:[Bool] = [        false,        
                                                       true    ]


BUG:
Commons/Configs.swift
    static var defaultProxySettingIdx: Int = 1
    static var Proxy:[Bool] = [        true,        
                                                       false    ]

     let proxySetting = GlobalSettings.shared.proxySetting.selectedOption().value
     agoraKit.setCloudProxy(AgoraCloudProxyType.init(rawValue: UInt(proxySetting)) ?? .noneProxy)

definition 
public enum AgoraCloudProxyType : UInt {
    /** Do not use the cloud proxy.
     */
    case noneProxy = 0

    /** The cloud proxy for the UDP protocol.
     */
    case udpProxy = 1

    /** The cloud proxy for the TCP (encrypted) protocol.
     */
    case tcpProxy = 2
}

**Comment by HenryRocken** [comment]
There is a BUG in the code.

Default is not to use proxy, and but proxy is initialized with "udpProxy = 1"

change the defaultProxySettingIdx: Int = 0 and change the order of Proxy to fix it.
Commons/Configs.swift

static var defaultProxySettingIdx: Int = 0
static var Proxy:[Bool] = [ false,
                                            true]

BUG:
Commons/Configs.swift
static var defaultProxySettingIdx: Int = 1
static var Proxy:[Bool] = [ true,
false ]

 let proxySetting = GlobalSettings.shared.proxySetting.selectedOption().value
 agoraKit.setCloudProxy(AgoraCloudProxyType.init(rawValue: UInt(proxySetting)) ?? .noneProxy)
definition
public enum AgoraCloudProxyType : UInt {
/** Do not use the cloud proxy.
*/
case noneProxy = 0

/** The cloud proxy for the UDP protocol.
 */
case udpProxy = 1

/** The cloud proxy for the TCP (encrypted) protocol.
 */
case tcpProxy = 2
}

**Comment by tamworth** [comment]
@HenryRocken you can try again using our latest version of the demo. the new SDK has optimized many things.
