### ISSUE TITLE
In Screen share, Start broadcast from iPhone stuck on the receiver end 

### ISSUE THREAD

**Issue by jamilshazad** [AgoraIO/API-Examples#159]
I am trying Screen share on my iPhone, when I click start broadcast it seems it's fine but on the receiver side, the screen gets stuck, and only a stuck image appears actually, other than that I can't see anything. When I tried screen share on an android phone it is working fine for the receiver side, I can see the screen on my iPhone. I am not getting warnings or errors in my console. please suggest

**Comment by yoreland** [comment]
Hi, can you help to modify the channel name to something different rather than default "ScreenShare" and reproduce the issue again, we will help you to check the issue from backend.

**Comment by jamilshazad** [comment]
okay, thank you to mention **the channel on both UI and screen share extension code** I was missing this part.

**Comment by yoreland** [comment]
Can you check if it is same problem as https://github.com/AgoraIO/API-Examples/issues/131
So far it is a known issue, and the fix is working-in-process. You could try to reduce encoder resolution and framerate to workaround

**Comment by jamilshazad** [comment]
hello, any news because I have to change the frame rate and resolution but still it left the channel in 20 seconds when I share the screen from iPhone.

**Comment by yoreland** [comment]
> hello, any news because I have to change the frame rate and resolution but still it left the channel in 20 seconds when I share the screen from iPhone. Getting Error 1. Detail is
> 
> ```
> USER_OFFLINE_DROPPED(1): The SDK timed out and the user dropped offline because no data
>          *              packet was received within a certain period of time. If a user quits the
>          *               call and the message is not passed to the SDK (due to an unreliable channel),
>          *               the SDK assumes the user dropped offline.
> ```

did you still get this issue?
USER_OFFLINE_DROPPED usually mean receiver can't receive packet than 20 seconds. 

Btw, did you check dev/screensharing branch?
