### ISSUE TITLE
外接了摄像头使用视频自采集功能，为什么还是调用了手机摄像头

### ISSUE THREAD

**Issue by SEVLT** [AgoraIO/API-Examples#160]
请问这是符合预期的吗？视频数据如何才能通过外接摄像头设备传入呢？

**Comment by yoreland** [comment]
这个示例只是展示自采集 push/mediaIO api的用法,可以自行进行摄像头的设备管理

**Comment by SEVLT** [comment]
好的，是不是可以理解为：
这个demo是演示自采集api用法，没有枚举当前可用摄像头并让用户选择功能，摄像头设备调用的是设备默认的，因为手机默认设备是自带摄像头，所以才导致我上述现象。

如果我上面理解正确的话，那想问一下如果我自己集成实现“设置采集设备为其他外接设备”，是需要
“先枚举出当前所有可用摄像头”
“然后参考agora官网自定义视频采集模块代码（push方式为例）：private var currentCamera = 目标摄像头”
这样的逻辑对吗？（不过我暂时没有找到枚举摄像头设备的api）

**Comment by yoreland** [comment]
目前只有在android支持前后摄像头的枚举
https://docs.agora.io/cn/Interactive%20Broadcast/API%20Reference/java/enumio_1_1agora_1_1rtc_1_1video_1_1_camera_capturer_configuration_1_1_c_a_m_e_r_a___d_i_r_e_c_t_i_o_n.html

可以自行使用可以采集外接摄像头的库采集后使用自采集api在rtc频道内发流

**Comment by SEVLT** [comment]
thx！

**Comment by SEVLT** [comment]
thx！
