### ISSUE TITLE
Android lib-raw-data doesn't work with app bundle

### ISSUE THREAD

**Issue by Jack29913** [AgoraIO/API-Examples#162]
It works fine with regular APK, getting callbacks and everything but with app bundle it doesn't work and not getting any callback. 
I don't see
`agora-raw-data-plugin: loadAgoraRtcEnginePlugin`
log.

 I only see
`agora-raw-data-plugin: setVideoDecodeByteBuffer uid: 67532, _javaDirectDecodeBuffer: 0xb6ba9010`

How can we make it work with app bundle? @yoreland 

Btw old raw-data-api-java works with app bundle, but we migrated to new latest agora version and can't use it anymore.

**Comment by Jack29913** [comment]
Solved it nevermind.

**Comment by thomasonweb** [comment]
Hi @Jack29913 

Do you mind sharing how you got this issue resolved?
Much appreciated!

Thomas
