### ISSUE TITLE
How can I get custom audio source without recording?

### ISSUE THREAD

**Issue by thkim0118** [AgoraIO/API-Examples#164]
We are reading built-in microphone data from Android JNI & Android recorder.

When using Agora, the built-in microphone data we made and the audio data received by Agora are mixed.

We only need built-in microphones from JNI we made and want to get Agora Low audio data only through registerAudioFrameObserver function.

Can we prevent Agora audio data from coming in with JNI audio data we made?

**Comment by plutoless** [comment]
maybe you can show part of your code to help me understand what you have done?

**Comment by thkim0118** [comment]
We read built-in microphone audio data from c++ native code.

And the Agora SDK doesn't set anything up for audio.

The current issue is that the audio data spoken by the other person is included in my internal microphone audio data, so when I save and listen to my internal audio data, I can hear the other person's audio (if I record the internal audio data, only my audio data should be heard).

**Comment by thkim0118** [comment]
I'm sorry. I'll fix it.


Using this "registerAudioFrameObserver", we receive embedded audio data and remotely received Agora data from our built-in audio callback.

Without this function, of course, only the built-in audio data is output and the remote Agora data is not output.

**Comment by thkim0118** [comment]
+ We are using "RtnEngine::registerAudioFrameObserver" and "RtcEngine::setExternalAudioSource" & "RtcEngine::pushExternalAudioFrame" at the same time. Is it okay to use it like this?

**Comment by thkim0118** [comment]
I solved.

We're using registerAudioFrameObserver and setExternalAudioSource.
So we specify an appropriate setting value for "setPlaybackAudioFrameParameters", "setRecordingAudioFrameParameters".
