### ISSUE TITLE
Microphone is not working when screen off

### ISSUE THREAD

**Issue by sleith** [AgoraIO/API-Examples#167]
Hi,
I found that when screen off for couple minutes, the microphone was stop working. But the speaker is still working (i can still hear the sound from counterpart).
When i turn screen on, the microphone instantly work again.

Please help. i tried on latest version 3.4.3 also still has this problem.
Thanks

**Comment by plutoless** [comment]
android or iOS? it could be system behavior that it stopped recording module after going offscreen for few minutes.

**Comment by sleith** [comment]
it's on Android. Might be so, i tried on 3 devices i have all same problem. can hear the incoming voice but can't send the voice.
Probably similar problem [here](https://stackoverflow.com/questions/54607665/why-audiorecord-is-not-recording-sound-when-device-fall-asleep-even-when-i-use-w)? or does it work just fine on your side?
Thanks

**Comment by yoreland** [comment]
> it's on Android. Might be so, i tried on 3 devices i have all same problem. can hear the incoming voice but can't send the voice.
> Probably similar problem [here](https://stackoverflow.com/questions/54607665/why-audiorecord-is-not-recording-sound-when-device-fall-asleep-even-when-i-use-w)? or does it work just fine on your side?
> Thanks

You may be interested check this article
https://docs.agora.io/en/Voice/faq/android_background

**Comment by sleith** [comment]
Thanks a lot for your help :)
