### ISSUE TITLE
App audio causes ios agora-ScreenShare-Exension demo to crash with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by natwales** [AgoraIO/API-Examples#169]
Tested on:
ios 14.6, Iphone Xr 
ios 13.7, iPhone 7

Steps to reproduce:

1. Build and run APIExample demo ios app
2. Launch extension via picker in APIExample container app and start screen broadcasting. 
3. Navigate to any app playing in app audio
4. Observe EXC_BAD_ACCESS crash occurring on [this line](https://github.com/AgoraIO/API-Examples/blob/a42f9839d92cf7bb4faa55c7a861bdde076174ed/iOS/Agora-ScreenShare-Extension/AgoraAudioTube.mm#L186) or [this line](https://github.com/AgoraIO/API-Examples/blob/a42f9839d92cf7bb4faa55c7a861bdde076174ed/iOS/Agora-ScreenShare-Extension/AgoraAudioTube.mm#L174).

Have observed similar behavior with mic audio as well. Seems to occur if I start the broadcast without the mic enabled and then enable the mic while the broadcast extension is running.

**Comment by yoreland** [comment]
it is a known issue and fixed in https://github.com/AgoraIO/API-Examples/tree/dev/screensharing

can you have check on that?
