### ISSUE TITLE
AgoraAudioCriticalSection causes ios agora-ScreenShare-Exension demo to crash with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by koogawa** [AgoraIO/API-Examples#177]
Tested on:
ios 14.6, iPad Pro
 
Steps to reproduce:
 
1. Build and run APIExample demo ios app
2. Launch extension via picker in APIExample container app and start screen broadcasting.
3. Navigate to any app playing in app audio
4. Observe EXC_BAD_ACCESS crash occurring on [this line](https://github.com/AgoraIO/API-Examples/blob/dev/screensharing/iOS/Agora-ScreenShare-Extension/AgoraAudioCriticalSection.h#L35).
 
![image](https://user-images.githubusercontent.com/893643/125398563-72095a00-e3ea-11eb-83af-a4e6b5d5df35.png)

Have observed similar behavior with mic audio as well. Seems to occur if I start the broadcast without the mic enabled and then enable the mic while the broadcast extension is running.

**Comment by yoreland** [comment]
can you have a try with dev/screensharing branch?

**Comment by koogawa** [comment]
@yoreland Yes, I have try with `dev/screensharing` branch.

**Comment by tamworth** [comment]
@koogawa you can try again using the new version of the API-Example.
