### ISSUE TITLE
Question about AgoraMeeting

### ISSUE THREAD

**Issue by apiphoomchu** [AgoraIO/API-Examples#178]
I have some question that if I want to join audio from another app by call the function

"agoraKit.joinChannel(byToken: token,channelId: channelid,info: nil,uid: 0 ,joinSuccess: nil)"
Token : same as AgoraMeeting
ChannelId : same as AgoraMeeting (I'm check from Agora dashboard)

But when I successfully call this function the audio doesn't come out from AgoraMeeting.
Did I do something wrong?

**Comment by yoreland** [comment]
did you check if onUserJoined call back from agora meeting side?

**Comment by Apiphoom** [comment]
Hmmmmmmmm the user join but sound won't come off.
BTW I want to add sound sharing in screen sharing how can I do it?

**Comment by yoreland** [comment]
sorry for late response.
Did you still meeting no sound issue for your integration?

For system sound sharing, you could check iOS screenScreen example in this repository.
