### ISSUE TITLE
ios app crash when stop broadcast

### ISSUE THREAD

**Issue by smkamranqadri** [AgoraIO/API-Examples#182]
I am trying to implement the screen share for iOS and it's working fine when the broadcast started, I can see the streaming but when I stop the broadcast the app got crashes, any help will be highly appreciated.

**Comment by yoreland** [comment]
whats your ios device model？

**Comment by smkamranqadri** [comment]
I was testing on ipad as well iPhone xs

**Comment by smkamranqadri** [comment]
surprisingly issue resolved when I change the target iOS version to 12 for the extension.

**Comment by tamworth** [comment]
@smkamranqadri you can try again using the new version of the API-Example.
