### ISSUE TITLE
创建一个AgoraRTCClient  频道名称如何生成

### ISSUE THREAD

**Issue by qm012** [AgoraIO/API-Examples#183]
@plutoless 
频道名称如何生成 下一个用户如何才能知道加入的是哪个频道?
感谢回复

**Comment by qm012** [comment]
@plutoless 公司有人工技术支持么 现在接入有很多概念需要技术支持

**Comment by yoreland** [comment]
这个需要通过自己的业务去同步这个信息

**Comment by yoreland** [comment]
> @plutoless 公司有人工技术支持么 现在接入有很多概念需要技术支持

这个进入agora console可以提交工单的

**Comment by qm012** [comment]
好的 感谢您的回复
