### ISSUE TITLE
RawMediaData-Swift-iOS: How to create a CVPixelBuffer from a AgoraVideoRawData

### ISSUE THREAD

**Issue by LittleRedLynn** [AgoraIO/API-Examples#189]
RawMediaData-Swift-iOS: **How to create a CVPixelBuffer from a AgoraVideoRawData**, whose type is 0(which refers to YUV420 in document)?
Here is my approach, but doesn't work, the pixel buffer just seems to be blank.
```
extension CVPixelBuffer{

    static func createFrom(_ agoraVideoRawData:AgoraVideoRawData) -> CVPixelBuffer?{
        let pixelFormat = kCVPixelFormatType_420YpCbCr8PlanarFullRange
        var cvPixelBuffer: CVPixelBuffer?
        
        CVPixelBufferCreate(
        nil,
        Int(agoraVideoRawData.width),
        Int(agoraVideoRawData.height),
        pixelFormat,
        nil,
        &cvPixelBuffer)
        
        guard cvPixelBuffer != nil else {
            return nil
        }
        
        CVPixelBufferLockBaseAddress(cvPixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
        let memoryLocationPointer = CVPixelBufferGetBaseAddress(cvPixelBuffer!)
        memoryLocationPointer?.copyMemory(from: agoraVideoRawData.yBuffer, byteCount: Int(agoraVideoRawData.yStride))
        let secondSegmentLocationPointer = UnsafeMutableRawPointer(mutating: memoryLocationPointer! + Int(agoraVideoRawData.yStride))
        secondSegmentLocationPointer.copyMemory(from: agoraVideoRawData.uBuffer, byteCount: Int(agoraVideoRawData.uStride))
        let thirdSegmentLocationPointer = UnsafeMutableRawPointer(mutating: secondSegmentLocationPointer + Int(agoraVideoRawData.uStride))
        thirdSegmentLocationPointer.copyMemory(from: agoraVideoRawData.vBuffer, byteCount: Int(agoraVideoRawData.vStride))
        CVPixelBufferUnlockBaseAddress(cvPixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
        
        return cvPixelBuffer
    }
}
```
----------------------------------------------------------------------------------------------------------------
The print information of a sample CVPixelBuffer created with my method is shown as followed:

<CVPixelBuffer 0x281a181e0 width=640 height=540 pixelFormat=f420 iosurface=0x0 planes=3>
<Plane 0 width=640 height=540 bytesPerRow=640>
<Plane 1 width=320 height=270 bytesPerRow=320>
<Plane 2 width=320 height=270 bytesPerRow=320>
<attributes={
    PixelFormatDescription =     {
        BitsPerComponent = 8;
        ComponentRange = FullRange;
        ContainsAlpha = 0;
        ContainsGrayscale = 0;
        ContainsRGB = 0;
        ContainsYCbCr = 1;
        PixelFormat = 1714696752;
        Planes =         (
                        {
                BitsPerBlock = 8;
                BlackBlock = {length = 1, bytes = 0x00};
                HorizontalSubsampling = 1;
                VerticalSubsampling = 1;
            },
                        {
                BitsPerBlock = 8;
                BlackBlock = {length = 1, bytes = 0x80};
                HorizontalSubsampling = 2;
                VerticalSubsampling = 2;
            },
                        {
                BitsPerBlock = 8;
                BlackBlock = {length = 1, bytes = 0x80};
                HorizontalSubsampling = 2;
                VerticalSubsampling = 2;
            }
        );
    };
} propagatedAttachments={
} nonPropagatedAttachments={
}>

**Comment by LittleRedLynn** [comment]
I got the answer myself, here is how I do, thanks my dear colleague.

```
extension CVPixelBuffer{
    
    static func createFrom(_ agoraVideoRawData:AgoraVideoRawData) -> CVPixelBuffer?{
        let pixelFormat = kCVPixelFormatType_420YpCbCr8VideoRange_8A_TriPlanar
        var cvPixelBuffer: CVPixelBuffer?
        CVPixelBufferCreate(
        nil,
        Int(agoraVideoRawData.width),
        Int(agoraVideoRawData.height),
        pixelFormat,
        nil,
        &cvPixelBuffer)
        
        guard cvPixelBuffer != nil else {
            return nil
        }
        
        CVPixelBufferLockBaseAddress(cvPixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
        let yPlanePointer = CVPixelBufferGetBaseAddressOfPlane(cvPixelBuffer!, 0)
        let uPlanePointer = CVPixelBufferGetBaseAddressOfPlane(cvPixelBuffer!, 1)
        let vPlanePointer = CVPixelBufferGetBaseAddressOfPlane(cvPixelBuffer!, 2)
        yPlanePointer?.copyMemory(from: agoraVideoRawData.yBuffer, byteCount: Int(agoraVideoRawData.yStride * agoraVideoRawData.height))
        uPlanePointer?.copyMemory(from: agoraVideoRawData.uBuffer, byteCount: Int(agoraVideoRawData.uStride * agoraVideoRawData.height / 2))
        vPlanePointer?.copyMemory(from: agoraVideoRawData.vBuffer, byteCount: Int(agoraVideoRawData.vStride * agoraVideoRawData.height / 2))
        CVPixelBufferUnlockBaseAddress(cvPixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
        
        return cvPixelBuffer
    }
}
```

**Comment by safad-srmg** [comment]
Hi @LittleRedLynn Can you please guide me how to save it as video file locally from CVPixelbuffer? Is there any sample snippet?
