### ISSUE TITLE
iOS Screen Sharing sound processing is incorrect

### ISSUE THREAD

**Issue by fpillet** [AgoraIO/API-Examples#203]
I have updated the example code so as to enable audio and see screen share from a remote user :
https://github.com/AgoraIO/API-Examples/pull/202

We are trying to get screen sharing in our own application and noticed that audio processing in the example is incorrect. The format conversions you are doing lead to sound that is like slowed down by 4 or 6 times. Not sure exactly where the problem is in your code, but sound processing example in ScreenShare for iOS / macOS should definitely be updated.

**Comment by yoreland** [comment]
We are working in progress of updating audio processing of this demo but it rely on a new version of sdk. It will be updated when new sdk is out.
