### ISSUE TITLE
CustomAudioSource example is broken

### ISSUE THREAD

**Issue by muojp** [AgoraIO/API-Examples#214]
How to reproduce:
- `git checkout 3.5.0` (or `master` branch)
- Check `Podfile` for dependency and make sure the project depends on `AgoraRtcEngine_iOS '3.5.0'`
- Fill in credentials, build, and open Example app
- Navigate to `Custom Audio Source`
- Specify channel name and connect to Agora server

Expected:
- Audio streams

Actual:
- Successfully connected to Agora server but no audio heard on other devices, nor on Dashboard
- `[self.agoraKit pushExternalAudioFrameRawData:...]` weirdly returns `NO` which implies something bad is happening inside Agora SDK. This method returns `YES` on older SDKs (3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5 works fine. 3.5.0 seems corrupt).

Notes:
- `Custom Audio Source` example seen in tag `3.4.2` works but `3.4.5` doesn't. It's NOT related to changes made for Agora SDK v3.4.5 because API-Examples-`3.4.2` depends on Agora v3.5.0 (see Podfile).

Tested on:
- Xcode 12.x and 13
- iPod touch 7th gen. iOS 14.7.1

**Comment by plutoless** [comment]
@muojp please wait for release 3.5.0.4 which should fix this issue. this version is about to release early next week.

**Comment by muojp** [comment]
@plutoless I appreciate your reply and great to hear this issue will be addressed in upcoming release :tada:
