### ISSUE TITLE
Agora Flutter - Live Facebook Video Screenshare feature not working with Error Code 3 : RtmpStreamingErrorCode.ConnectionTimeout

### ISSUE THREAD

**Issue by fldvlpr** [AgoraIO/API-Examples#231]
Hello @AgoraIO @ShengQiangLiu @yoreland @CLuCheng @LichKing-2234 ,

I was trying out flutter agora sdk with facebook live feature,

I've followed the following link for fb code and setup part,
[](https://developers.facebook.com/docs/live-video-api/getting-started/
)
After that I've been **generating token** and getting **secure_stream_url**, I'm passing it to the agoraEngine's addPublishStreamUrl() method.

But, every time I'm getting an error in agora event "**rtmpStreamingStateChanged**" callback,

```
rtmpStreamingStateChanged:
        (String url, RtmpStreamingState state, RtmpStreamingErrorCode errCode) {
      print("rtmpStreamingStateChanged : ${state} : ${errCode.toString()} : ${errCode.index}");
    }

```

Error Log :
**rtmpStreamingStateChanged : RtmpStreamingState.Failure : RtmpStreamingErrorCode.ConnectionTimeout : 3**

Can anyone please suggest a solution?

I'm using **flutter SDK 2.2.3** and https://pub.dev/packages/agora_rtc_engine with version 4.0.7

Thanks

**Comment by tamworth** [comment]
@fldvlpr please refer to the link:
https://docs.agora.io/en/video-calling/core-functionality/screen-sharing?platform=flutter
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/screen_sharing/screen_sharing.dart
