### ISSUE TITLE
is there any posible way to  hide a spesic button  while sharing screen

### ISSUE THREAD

**Issue by EworkitSrl** [AgoraIO/API-Examples#234]

**Comment by yoreland** [comment]
do you mean the replay kit dialog for iOS?

**Comment by EworkitSrl** [comment]
no . i i am a android application developer and i use android studio. i have a requirement to hide a button while screen sharing . but i don't know it is possibile or not

**Comment by yoreland** [comment]
So seems the button exist on your app but you want to hide it during streaming, right?
It sounds something like watermark. You could check the current screenScreening example, then you may need to use openCV to add water mark before push to Agora SDK

**Comment by bandrarom** [comment]
@yoreland 
I have use agora sdk with uvc camer library in android studio  and successfully renderind the video . But there is a problem that while streaming video from uvc camera audio get from mobile microphone. sop i read the agora documenttation and  i apply the agora external audio source.

 mRtcEngine.setExternalAudioSource(true, 44100, 1);

                            mRtcEngine.pushExternalAudioFrame(data, length);

But  i didn't streaming audio . i can only hear a noice like  tiktik tik tik .
so do you have any idea about this ?
