### ISSUE TITLE
How to setup cloud recording service with Microsoft Azure  - Storage Config

### ISSUE THREAD

**Issue by adarsh-technocrat** [AgoraIO/API-Examples#236]
Hi everyone I have built an Agora Cloud recording Server and using Microsoft Azure for storing Audio recordings of individual users. But I am facing some issues with the storage config part  I am not getting the required credential from Azure which are required in the storage config object.

**Below is the object body** 
```json

{
        "cname": cname,
        "uid": uid,
        "clientRequest": {
          "token": token,
          "recordingConfig": {
            "channelType": 0,
            "streamTypes": 0,
            "videoStreamType": 0,
            "maxIdleTime": 120,
            "subscribeUidGroup": 0
          },
          "storageConfig": {
            "vendor": 5,
            "region": 0,
            "bucket": Config.BUCKET,
            "accessKey": Config.ACCESS_KEY,
            "secretKey": "{{SecretKey}}"
          }
        }
      }
```

I need a **Bucket**, **accessKey**, and **secretKey** in order to store audio files in Azure storage  I manage to get the `access key` but how I can get the other two from azure.

it would be really helpful if anyone can provide steps to setup **storageConfig** with Microsoft Azure :)

Thank you 

cc: @yoreland

**Comment by yoreland** [comment]
Did you check the document on https://docs.agora.io/en/cloud-recording/cloud_recording_api_rest?platform=RESTful
I personally don't have a active Azure account, usually these information could be found from access key management
https://docs.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal

**Comment by adarsh-technocrat** [comment]
> 

Yes, @yoreland I have checked the  Cloud recording API document. I think this storage config object is related to the Amazon S3 bucket, there is no example for Azure Microsoft or even GCP.

I got the Access Key  and Bucket name of the storage  but not the Secret key  so whenever I make a `start ` call I get in response `resource id` and `sid` and when I make a `stop `call I get **403** error response  this means the API couldn't get access to storage 

is there is any example of GCP?

**Comment by adarsh-technocrat** [comment]
I am getting this response when I make  a stop call 

```json
{
   "resourceId":"Etkl6g-zSB7EpP-Da1zN63dq8zdhhwI1ia8deuCa71TI_0DgXb2DMnMvJqnz4gtyoYOh7CXOu_E-75Rmtg0TfqMUTSAEVWRcQRj8GpB-0cS7AmO99d0Xgv93qv9wQEcmuWQmO_8lvTjWtWGERMNrLAdEHXTam8hnQqkL7B-10ndfXNmJLI1j958EnE7wrgn1PYjC-T-okGDAMTKYtbK3kFZfwk0nk3pu0GRXgWn9F4rBt6Rcc7d7z62nwetCrpoEG4B4dr0esQxPhdI9FJSSjoMtz3oSPrecbRlXjpaa9vNL0YucK3GdGzVebh7IbA6WE1UwY0OosIF2LDbRq3R9rZLYjNHQ2K-DfG9bA-TVgCs",
   "sid":"7f395f4c0440d442237a2ba49ed15e0b",
   "code":404,
   "serverResponse":{
      "command":"StopCloudRecorder",
      "payload":{
         "message":"Failed to find worker."
      },
      "subscribeModeBitmask":2,
      "vid":"493738"
   }
}
```

**Comment by yoreland** [comment]
This problem usually due to the region for oss not supported, better try to select a region where nearer with you

**Comment by adarsh-technocrat** [comment]
Here is the Solution : 


**vendor” should be set to 5 for Microsoft Azure
 “accessKey” should refer to your storage account name
“secretKey” refers to your access key, you can find the same in your Azure Storage Account dashboard, under “Access Key” -> “Show keys”.
For “bucket” you should input your container name.
Finally for “fileNamePrefix” (optional) you can pass an array of strings indicating the path of your recording files within your container.**

**Comment by adarsh-technocrat** [comment]
Thanks, @yoreland  closing this issue :)
