### ISSUE TITLE
音频自采集(PCM) 报错 push result: -2

### ISSUE THREAD

**Issue by 673697831** [AgoraIO/API-Examples#237]
API-Examles中音频自采集(PCM)报错，onAudioFrame回调后，agoraKit.pushExternalAudioFrameRawData返回值为-2.控制台一直输出

push result: -2
push result: -2
push result: -2
push result: -2
push result: -2
push result: -2

**Comment by yoreland** [comment]
是iOS还是macOS的示例呢?

**Comment by 673697831** [comment]
iOS的，在这个git上面close了在master不行。在官网上下载的zip包也不行。

**Comment by 673697831** [comment]
token用的是临时的，有关系吗。

**Comment by 673697831** [comment]
还有在真机上，好像没声音，滑动的ui也有bug，布局也报错了。![image](https://user-images.githubusercontent.com/8503279/145217930-c9eb6081-9c1b-48a4-8595-561a99eee765.png)![1891638970467_ pic](https://user-images.githubusercontent.com/8503279/145217483-0743aca9-e432-4c6d-ab07-3a54a00130d0.jpg)

**Comment by yoreland** [comment]
修复的代码:
func onAudioFrame(data: UnsafeMutablePointer<UInt8>, samples: UInt) {
        let frame = AgoraAudioFrame()
        frame.buffer = UnsafeMutableRawPointer(data)
        frame.samplesPerSec = Int(sampleRate)
        frame.channels = Int(channel)
        frame.bytesPerSample = 2
        frame.samplesPerChannel = self.samples / 2
        let ret = agoraKit.pushExternalAudioFrameRawData(pushPos, frame: frame)
        print("push result: \(ret)")
    }

会马上更新一下分支
