### ISSUE TITLE
Compile error caused by old RTC SDK version

### ISSUE THREAD

**Issue by yamasite** [AgoraIO/API-Examples#244]
The dependency `api 'io.agora.rtc:full-sdk:3.5.2'` in

https://github.com/AgoraIO/API-Examples/blob/master/Android/APIExample/lib-component/build.gradle

should be updated to `api 'io.agora.rtc:full-sdk:3.6.0'`

Otherwise, the project won't compile.

@yoreland

**Comment by yamasite** [comment]
Besides, if you use 3.6.0, the app shows the following errors when running:

```
2021-12-23 11:44:11.322 2351-2351/io.agora.api.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.agora.api.example, PID: 2351
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.agora.api.example-1/base.apk"],nativeLibraryDirectories=[/data/app/io.agora.api.example-1/lib/x86, /data/app/io.agora.api.example-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libagora-soundtouch.so"
```

**Comment by yoreland** [comment]
我来处理下

**Comment by yoreland** [comment]
> Besides, if you use 3.6.0, the app shows the following errors when running in an Emulator:
> 
> ```
> 2021-12-23 11:44:11.322 2351-2351/io.agora.api.example E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: io.agora.api.example, PID: 2351
>     java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.agora.api.example-1/base.apk"],nativeLibraryDirectories=[/data/app/io.agora.api.example-1/lib/x86, /data/app/io.agora.api.example-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libagora-soundtouch.so"
> ```

Btw, you could try with  
api 'io.agora.rtc:full-sdk:3.6.0.1'
