### ISSUE TITLE
How to invalidate agora dynamic token?

### ISSUE THREAD

**Issue by aaukhatov** [AgoraIO/API-Examples#250]
I would like to invalidate a key what I issued.
How can I to do that?

**Comment by AttilaTheFun** [comment]
I would like to be able to revoke tokens as well.

**Comment by plutoless** [comment]
@AttilaTheFun currently we don't support that. in which circumstances you need this feature?

**Comment by aaukhatov** [comment]
@plutoless For instance, in some security cases.

**Comment by plutoless** [comment]
@aaukhatov how abt set the token expire time shorter and renew only if needed?
