### ISSUE TITLE
How to screenshare in full HD mode?

### ISSUE THREAD

**Issue by sagar1garg** [AgoraIO/API-Examples#253]
@yoreland currently the screen share has no option to capture screen in HD mode. Further it doesn't make use of the mediaRecorder mode where in I can set 
CamcorderProfile cpHigh = CamcorderProfile.get(CamcorderProfile.QUALITY_HIGH);                    

How can this be achieved using the current lib:screensharing?

**Comment by yoreland** [comment]
the 3.6.2 android SDK will add a new API startScreenCapture, and lib:screensharing will be remove then.
I will update it when the new sdk released.

**Comment by sagar1garg** [comment]
What's the timeline for v3.6.2? We use screenshare extensively in our app this is critical for us. @yoreland

**Comment by yoreland** [comment]
it will be in next week according to current plan.
but if it is hard for you for upgrading, you might try to use this api setVideoEncoderConfigration

**Comment by sagar1garg** [comment]
Upgrading should be fine but I use it for game streaming. Hopefully it will also take away cases of overheating and screenshare service crashing and immediately restarting (in case of lib:screensharing) @yoreland

**Comment by sagar1garg** [comment]
Hi @yoreland is v3.6.2 released?

**Comment by vishalkumarsinghvi** [comment]
@yoreland Any update regarding screen sharing API?.
