### ISSUE TITLE
Crash on Raw Video/Audio Data

### ISSUE THREAD

**Issue by piyush921** [AgoraIO/API-Examples#256]
After building Android Example, When I click on the "Raw video/Audio data" feature it opens the screen with a small description, and then clicking on the "Next step" button it's crashing. 
After debugging, I found out its Native crash (crash logs attached). I think the problem is in Agora SDK. 
Please help.
[tombstone_04.txt](https://github.com/AgoraIO/API-Examples/files/7950038/tombstone_04.txt)

**Comment by yoreland** [comment]
Thanks for report this issue, we will check and update. Currently it seems the issue is related with c++ header alignment on lib-raw-data module.

**Comment by yoreland** [comment]
@piyush921 it is just updated and fixed, you could check the same
