### ISSUE TITLE
'AgoraReplayKitExtension/AgoraReplayKitExt.h' file not found

### ISSUE THREAD

**Issue by ideal8173** [AgoraIO/API-Examples#261]
I have take update code by this branch (dev/3.6.2/screen-share-socket-ios). But I am facing this type error.
'AgoraReplayKitExtension/AgoraReplayKitExt.h' file not found

**Comment by yoreland** [comment]
Hi, it is still a dev branch as 3.6.2 yet published, but it should be very recently, I will update here when it is released.

**Comment by ideal8173** [comment]
Ok, thanks i am waiting for your reply.

**Comment by yoreland** [comment]
Hi, 3.6.2 was just released from homepage, but unfortunately, replayKitExtension feature wasn't decided to publish. There are still some related issues need to address and might be released in next patch.
sorry for late response, but we will keep update when it is ready.

**Comment by imuhammadnadeem** [comment]
I fixed this issue by changing 

#import "AgoraReplayKitExt.h"

with

#import "AgoraReplayKitExtension/AgoraReplayKitExt.h"
