### ISSUE TITLE
OnScreenCaptureInfoUpdated dosen't work

### ISSUE THREAD

**Issue by seungsunkim** [AgoraIO/API-Examples#268]
I used the StartScreenCaptureByScreenRect function to start sharing the screen.
The OnScreenCaptureInfoUpdated event is supposed to be triggered when I start sharing the screen, but the trigger event doesn't come on.

How can I solve this?

**Comment by yamasite** [comment]
Per the [documentation](https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/cpp/classagora_1_1rtc_1_1_i_rtc_engine_event_handler.html?platform=Windows#aa3c5bcfd0f1c4c136b064c3a6feed3f1), when you call [startScreenCaptureByDisplayId](https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/cpp/classagora_1_1rtc_1_1_i_rtc_engine.html#a4fe820ff5b886636494404fc7ed4ee0d) or [startScreenCaptureByScreenRect](https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/cpp/classagora_1_1rtc_1_1_i_rtc_engine.html#a41893fe9a0ca49c054bf6dbd7d9d68f5) to start screen sharing and use the `excludeWindowList` attribute to block the specified window, the SDK triggers this callback if the window blocking fails.

Have you set the `excludeWindowList` attribute to specify a list of IDs of windows to be blocked? And are you sure that the window blocking fails?

**Comment by seungsunkim** [comment]
@yamasite The excludeWindowList property is not set.
I was wrong.
Thanks for the reply.
