### ISSUE TITLE
iOS Picture in Picture

### ISSUE THREAD

**Issue by rmickeyd** [AgoraIO/API-Examples#281]
I am integrating picture in picture and I am able to get the demo project fully working. When I integrate into my actual app the video stream goes to frozen state when backgrounding app with error code 10 (sdk in background) although audio continues to work. The only thing I can see that is different between the demo project and my actual app is the demo joins channel through RtcEngine and my app joins through RtcChannel. Is this a limitation of RtcChannel implementation or is there something I am missing?

**Comment by plutoless** [comment]
sorry which platform you are running with? Android or iOS?

**Comment by plutoless** [comment]
have you checked this in your project?
![image](https://user-images.githubusercontent.com/471561/175192577-ffa73047-d13f-41fc-bf07-eb096c6e3680.png)

**Comment by rmickeyd** [comment]
Like I mentioned the audio works when in background. So yes this is checked. We have been using Agora in background mode for almost 2 years without Picture in Picture. We are now trying to add Picture in Picture support

**Comment by plutoless** [comment]
umm is there any chance you can help provide a minimal reproducible project so that i can investigate? It's working from my end so it would be difficult for me to guess what is happening.

**Comment by rmickeyd** [comment]
Ok I did some more testing and no longer believe it is related to RtcEngine vs RtcChannel. 

If I test the call with 1 iPhone and the agora web demo the PiP seems to work perfectly on the phone.

If I test the call with 2 iPhones it stops working. This is fully reproducible in the agora provided api example project when using 2 phones.

**Comment by rmickeyd** [comment]
Version 3.7.0-r.3 from the SPM repo works along with adding this line of code before joining channels.

            agoraKit.setParameters("{\"che.video.enable_bg_hw_decodec\": true}")

**Comment by indrac** [comment]
hi @rmickeyd @plutoless , I experienced the same issue. when my app in the background mode, the agora video goes frozen (but the audio works). I'm using AgoraRtcEngine_iOS 4.5.0 and did implement exactly the same code in API-Examples repo for picture in picture. Any clues on how to solve the isssue?

**Comment by dunghoangpg** [comment]
@indrac  do you have any solution for this?
