### ISSUE TITLE
pod成功，项目运行不起来

### ISSUE THREAD

**Issue by xhj0307** [AgoraIO/API-Examples#286]
ld: building for iOS, but linking in dylib file (/Users/iss/Library/Developer/Xcode/DerivedData/APIExample-dwprqnyayoqjcxbhecbwsicqxshd/Build/Products/Debug-iphoneos/AgoraAIDenoiseExtension.framework/AgoraAIDenoiseExtension) built for iOS Simulator, file '/Users/iss/Library/Developer/Xcode/DerivedData/APIExample-dwprqnyayoqjcxbhecbwsicqxshd/Build/Products/Debug-iphoneos/AgoraAIDenoiseExtension.framework/AgoraAIDenoiseExtension' for architecture arm64

**Comment by cleven1** [comment]
请使用新版本 pod 'AgoraRtcEngine_iOS', '~> 3.7.0.3'
