### ISSUE TITLE
android sdk-版本 4.0.1- 用c++开发，初始化 m_rtcEngine->initialize(ctx); 闪退

### ISSUE THREAD

**Issue by ydi-mua** [AgoraIO/API-Examples#313]
c++ 接入rtc  android，  引用 android sdk-版本 4.0.1 中的 hide-level/include 下的头文件和arm64-v8a下的so库，m_rtcEngine->initialize(ctx); 程序发生闪退

**Comment by plutoless** [comment]
你好，请问这边是直接跑的我们api example吗? 还是您自己集成SDK的，如果是自己集成的，能提供一下您这边的复现项目吗

**Comment by baiduyixianijiu** [comment]
> 你好，请问这边是直接跑的我们api example吗? 还是您自己集成SDK的，如果是自己集成的，能提供一下您这边的复现项目吗

自己SDK集成的，需要依赖我们这边的工具平台，不好提供复现项目，我看api example 集成android版本是java开发的，但是 我是用c++来集成的，引用的是  android sdk-版本 4.0.1 中的 hide-level/include 下的头文件和arm64-v8a下的so库，就出现了闪退问题
void AgoraEngine::join_channel(const String p_token, const String p_channel) {
    agora_engine = createAgoraRtcEngine();
    if(agora_engine){
        RtcEngineContext ctx;
        ctx.eventHandler = this;
        ctx.appId = AGORA_APP_ID;
        agora_engine->initialize(ctx);  //定位到这里，程序出现闪退
    }
}

**Comment by plutoless** [comment]
@baiduyixianijiu 您好，我不太确定您的工具平台大概做了一些什么处理，这样不太好定位问题，你们是类似做了jni wrapper吗? 这边闪退的时候崩溃栈能不能发一下，但如果这边无法提供复现项目，我们帮您定位问题的效率也会比较低
