### ISSUE TITLE
No mic when screensharing on iOS

### ISSUE THREAD

**Issue by jonah-katz** [AgoraIO/API-Examples#321]
It seems when you do screensharing on iOS, the mic doesn't go through. The old SDK/example [had additional processing](https://github.com/AgoraIO/Advanced-Video/blob/87a01b29b637dfcd55fa327b86eaf4f941e801d0/iOS%26macOS/Agora-Screen-Sharing/Agora-Screen-Sharing-iOS-Broadcast/Agora-Screen-Sharing-iOS-Broadcast-Bridging-Header.h). How do we do it on the new SDK?

**Comment by tamworth** [comment]
@jonah-katz you can try again using the new version of the API-Example.
