### ISSUE TITLE
Continuous Log Message in iOS 4.1.0

### ISSUE THREAD

**Issue by rohitphogat19** [AgoraIO/API-Examples#327]
Hi team I am getting continuous log message in Xcode Console.
Broadcaster App is using Agora 3.7.1
Audience App is using Agora 4.1.0

Message is in below format:
Incorrect NSStringEncoding value 0x8000100 detected. Assuming NSASCIIStringEncoding. Will stop this compatibility mapping behavior in the near future.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/36146505/210179914-b6950100-04a4-4ce8-b2d3-1d0eef041b45.png">

**Comment by plutoless** [comment]
@rohitphogat19 hi we have already detected this issue and it's caused by latest iOS system upgrade. We will fix this issue in next release 4.1.1

**Comment by rohitphogat19** [comment]
@plutoless What is expected release date for 4.1.1?

**Comment by plutoless** [comment]
@rohitphogat19 it's a minor release so should be mid-late Jan.
