### ISSUE TITLE
 Agora cloud recording's best fit layout is not working properly

### ISSUE THREAD

**Issue by noob0701** [AgoraIO/API-Examples#341]
I am using agora for live streaming, there can be multiple host in a stream like a video call, and using agora cloud recording to record the stream, but in my recordings screen is not splitting up properly according to number of users, i am using bestFitLayout in which i have to pass height and width every time a user joins or leave the stream. Is their any way that agora can dynamically get height and width?

I am using this url ${agoraUrl}/resourceid/${resourceId}/mode/mix/start to start cloud recording.

```{
        cname: channelName,
        uid: uid,
        clientRequest: {
            token: token,
            recordingConfig: {
                channelType: 0,
                streamTypes: 2,
                audioProfile: 1,
                videoStreamType: 0,
                maxIdleTime: 120,
                transcodingConfig:
                {
                    height: 360,
                    width: 640,
                    bitrate: 500,
                    fps: 15,
                    mixedVideoLayout: 1
                }
            },
            recordingFileConfig: {
                avFileType: [
                    "hls",
                    "mp4"
                ]
            },
            storageConfig: {
                vendor: 1,
                region: 14,
                bucket: process.env.AWS_S3_RAW_BUCKET_NAME,
                accessKey: process.env.AWS_ACCESS_KEY_ID,
                secretKey: process.env.AWS_SECRET_KEY,
                fileNamePrefix: [
                    channelName,
                    sidLength
                ]
            }
        }
    }```
I want cloud recording to dynamically split screen according to number of users.

**Comment by plutoless** [comment]
transcodingConfig:
                {
                    height: 360,
                    width: 640,
                    bitrate: 500,
                    fps: 15,
                    mixedVideoLayout: 1
                }

if you are talking abt this, this is canvas resolution, not video's. when you say it's not split up the screens by user properly, do you have an example screenshot?
