### ISSUE TITLE
接口joinChannelEx返回错误码-8的问题

### ISSUE THREAD

**Issue by ahwywu** [AgoraIO/API-Examples#345]
在调用joinChannelEx时，如果最后一个参数IRtcEngineEventHandler* eventHandler所传实例是IRtcEngineEventHandlerEx的子类，这个时候就会返回错误码-8，看-8对应的错误原因是在调用了startEchoTest后未调用stopEchoTest，实际情况是并没有调用startEchoTest。即使在调用joinChannelEx前尝试调用stopEchoTest，依然返回-8

**Comment by xgfd3** [comment]
8：ERR_INVALID_STATE，加入频道时状态错误，可以检查下是否重复加频道，或者rtcEngine是否初始化错误
