### ISSUE TITLE
Implement Video playback for video calls

### ISSUE THREAD

**Issue by Sreesanth46** [AgoraIO/API-Examples#347]
If a user joins last on a video call the user should be able to watch what happened on the call before joining the call.

- The user should be able to join to the live call
- The user should also be able to play the video playback of the video call. Something "like" live in youtube.

Is there a way or example that I can refer to implement thin in agora.

**Comment by tamworth** [comment]
@Sreesanth46 I think this is what you're looking for:
Join a call with video: [Video Call Overview](https://docs.agora.io/en/video-calling/overview/product-overview?platform=android)
Video playback using cloud recording: [Cloud Recording Overview](https://docs.agora.io/en/cloud-recording/overview/product-overview)"
