### ISSUE TITLE
engine.muteLocalAudioStream(true), it doesn't work.

### ISSUE THREAD

**Issue by Hyun-Jegal** [AgoraIO/API-Examples#369]
When reading an audio file and sending audio data using engine.pushExternalAudioFrame(...), audio is played from the speaker.
What should I do to prevent sound from the speaker at this time?
Even if you use engine.muteLocalAudioStream(true), it doesn't work.

**Comment by plutoless** [comment]
if you just would like to play audio file and share it across channel, you may choose to use our mediaplayer apis to open and play it. you don't need to use pushExternalAudioFrame to do this yourself.
