### ISSUE TITLE
How to use IVideoSource in agora 4.2.6

### ISSUE THREAD

**Issue by krunalpaliwal** [AgoraIO/API-Examples#371]
In the older version of Agora, I use the IVideoSource to set the custom video frames but when I upgrade the version of Agora there is no such method. What is the alternative way to use the same? I am using Android version of **implementation 'io.agora.rtc:full-sdk:4.2.6'**

**Comment by plutoless** [comment]
hi @krunalpaliwal  please follow the guide in https://github.com/AgoraIO/API-Examples/tree/main/iOS/APIExample/APIExample/Examples/Advanced/CustomVideoSourcePush
to understand how to implement custom video source.

**Comment by krunalpaliwal** [comment]
@plutoless Thank you. 
CustomVideo is not the issue for me. The version I used is 4.2.6 this method is not available. Now, I have to upgrade to the new version but due to this, I couldn't.

**Comment by plutoless** [comment]
@plutoless the iVideoSource has been removed in 4.x SDK. it's recommended to use push approach to implement custom video source
