### ISSUE TITLE
iOS `setVideoFrameDelegate` does not work as expected.

### ISSUE THREAD

**Issue by vince-hz** [AgoraIO/API-Examples#378]
I want to do background removal. So I try to modify video raw data by myself. I download the project with commit hash ['0ec9b443b880d7ccae058c6adfd2f1ca4d77e8be'](https://github.com/AgoraIO/API-Examples/tree/0ec9b443b880d7ccae058c6adfd2f1ca4d77e8be). After setup, I clicked the 'Raw Video Data' button on the main screen. Then I join a channel successfully. But the `onCaptureVideoFrame:` function was not called as expected. My device is iPad Air4 and iOS version 17.3.1.

**Comment by tamworth** [comment]
Please update AgoraRtcEngine_iOS to version 4.3.1 or 4.3.2 in the Podfile; we have fixed the issue.

Additionally, if you want to enable background removal, you can refer to the functionalities in the link below.
https://docs.agora.io/en/video-calling/advanced-features/virtual-background?platform=ios
