### ISSUE TITLE
Agora cant send livestream video using FU SDK

### ISSUE THREAD

**Issue by manhpv-1697** [AgoraIO/API-Examples#397]
Im using FU for beauty but when viewer join channel. The channel has only audio
For beauty, im using CameraRenderer for render beauty effect. Your example only use a basic beauty for changed light, it not useful

**Comment by xgfd3** [comment]
The FU thirdparty beauty case is using rtc sdk raw video interface（rtcEngine.registerVideoFramerObserver），you can use this way to integrate FU beauty sdk.
The CameraRenderer is an camera capture compose provided by FU. If you want to use CameraRenderer, you can refer to the pushExternalVideoFrame case. You should register video frame callback to CameraRenderer, then transform video data to agoar video frame for pushing it to sdk by pushExteranlVideoFrame api. This way is not suggested.

**Comment by manhpv-1697** [comment]
@xgfd3 After debug your souce code demo, i found a issue  When you call FurenderKit.renderWithInput(input), you didn't set input.renderConfig.isNeedBufferReturn = true then FuRenderKit alway return output without image frame
