### ISSUE TITLE
AgoraMeeting issue 

### ISSUE THREAD

**Issue by Apiphoom** [AgoraIO/API-Examples#95]
Describe the bug

I have some problem in AgoraMeeting can you please help me solve the issue? Thank you very much
(You can see the issue in AgoraIO-Usecase/AgoraMeeting#8)

@yoreland
@plutoless

To Reproduce
1).Run sample project (I follow all the guide that you provided)

Smartphone (please complete the following information):

Device: iPad Pro 11 inch 2020
OS: 14.0

**Comment by Apiphoom** [comment]
Please help. I think my brain is dead right now ;-;

**Comment by Apiphoom** [comment]
Already fix it.

**Comment by plutoless** [comment]
sorry for late reply :) notice the issue has been resolved
